### ISSUE TITLE
Inquiry to reconstruct directed acyclic graphs

### ISSUE THREAD

**Issue by mdbahadur** [lingfeiwang/findr-R#2]
Lingfei,
Thanks for providing the R package for findr. I’ve some inquiry to run findr package. I ran your provided example (geuvadis data) in findr package as follows:
# Step-1: To predict pairwise regulation probability with expression and eQTL data:
Out1=findr.pij_gassist(geuvadis$dg, geuvadis$dt,geuvadis$dt2)
where,
geuvadis$dg is 10 X 360 
geuvadis$dt is 10 X 360 
geuvadis$dt2 is 3000 X 360 
Then the output of Out1 is 10 X 3000
# Step-2: To reconstruct directed acyclic graphs
prior= Out1 [1:dim(Out1)[1],1:dim(Out1)[1]]
net=findr.netr_one_greedy(prior)
The output of net is 10 X 10. The output is a logical matrix. Element [i,j]= TRUE if an edge exists from node i to j on the reconstructed network, and FALSE otherwise.
Could you please explain this output?

If I ran the following then got an error
net=findr.netr_one_greedy(Out1) (if I’d like to use whole matrix of output from step-1)
Error: Wrong input data shapes. Check dp is a square matrix.

Why input matrix for findr.netr_one_greedy need a square matrix? 

Note, I'm expecting the output (inferred graph) of  findr.netr_one_greedy would be 10 X 3000, which 10 miRNA expression has 3000 targets. Is anything wrong of my understanding? I’ll be very happy, if you explain it.

Thanks in advance for your co-operation.

Regards,
Badsha

**Comment by lingfeiwang** [comment]
Your procedure is correct.

findr.netr_one_greedy constructs a Bayesian network with greedy algorithm. Bayesian network requires the network not to contain any circles. This restriction only matters on the square part of the matrix, i.e. genes that can have both incoming and out-going regulations. Genes without any out-going regulations can be the target of all other genes, and vice versa. Therefore, extending a Bayesian network to non-square matrix/network is trivial and not addressed in Findr.

**Comment by audreyqyfu** [comment]
Lingfei, I'm interested in this question, too, but baffled by your answer.  With the GEUVADIS example, is findr.netr_one_greedy constructing a DAG for the 10 miRNAs only, or for 10 miRNAs and the first 10 gene expression nodes, or for the first 10 gene expression nodes?  None of them seems to make sense, if the goal was to find the targets of 10 miRNAs from 3000 gene expressions.  Thanks.

Audrey

**Comment by lingfeiwang** [comment]
Thank you both for raising the question.

You are right that the two-step pipeline does not make sense, although the data dimensions conform functional requirements. The Bayesian network reconstruction function is supposed to accept an existing directed graph in dense matrix form, so the lists of source and target nodes should be identical.

Although this function has been implemented, it was not used in the current publication, and not expected to be picked up by Findr's users. We planned to formally release this function in our next paper. However, as you have expressed increasing interest, I am happy to improve the documentation in the next release.

**Comment by audreyqyfu** [comment]
I didn't mean to imply that the two-step pipeline was wrong; we're in fact trying to understand what it does.  

We're trying to replicate the results in your paper and to compare with our method.  If findr.netr_one_greedy wasn't used in the paper, which functions did you use for the DREAM5 data and for the GEUVADIS data?

Thanks,
Audrey

**Comment by lingfeiwang** [comment]
I see. The novel, traditional, and correlation tests correspond to findr.pij_gassist, findr.pij_gassist_trad, and findr.pij_rank respectively.

**Comment by audreyqyfu** [comment]
thanks, Lingfei.  In the DREAM5 data, how did you split the gene expression data?  Suppose dg is the eQTLs, dtq is the gene expression with eQTLs, and dtnq is the genes without eQTLs.  Did you do this?
`findr.pij_gassist(dg, dtq, rbind (dtq, dtnq))
`
Since in principle any gene can be a regulator and a target, dtq may need to appear in both the 2nd and 3rd arguments.  Should dtq be split into two sets, say, dtq1 and dtq2, and run findr twice as follows?
`
findr.pij_gassist(dg, dtq1, rbind (dtq2, dtnq))
`
`
findr.pij_gassist(dg, dtq2, rbind (dtq1, dtnq))
`
Thanks!

**Comment by lingfeiwang** [comment]
When the source gene list and target gene list overlap, Findr only handles the case that one is a subset of the other. Regardless of which is the subset, they need to be rearranged so that the top part of the superset gene list is identical with the whole subset gene list, and with the option nodiag=TRUE. For example, when the source gene list is a subset of the target gene list, because some genes don't have eQTLs, the target gene list should be a concatenation of the source gene list and the list of genes without eQTLs. Another example is when you have the same set of genes as source and target, the two matrices should be identical.

Therefore, in R you can use the code
`findr.pij_gassist(dg, dtq, rbind (dtq, dtnq),nodiag=T)`
although we used the binary interface in the analysis.

There's no need to rerun the analysis as pairwise probabilities are already computed in the above command.

In Fig2 EF and S1 Table of https://doi.org/10.1371/journal.pcbi.1005703, we included cis- and trans-eQTLs regardless, and the R equivalent command is:
`findr.pij_gassist(dg, dt, dt,nodiag=T)`

**Comment by audreyqyfu** [comment]
Thanks!  This is very helpful.

**Comment by lingfeiwang** [comment]
Examples have been updated to address this issue in version 1.0.3.
