### ISSUE TITLE
Different posteriors with different subsets of `dt`

### ISSUE THREAD

**Issue by sritchie73** [lingfeiwang/findr-R#4]
Hi, 

I've found that I get completely different posterior probabilities when running Findr in two different ways:

 - Running as intended with all exposures (dt), their genetic instruments (dc), and all possible downstream targets (dt2).
 - Running each exposure separately on all possible downstream targets.

E.g.:

```{r}
findr.pij_cassist(anchors, exposure, targets, nodiag=TRUE)
```

will return different posteriors for the first exposure when compared to:

```{r}
findr.pij_cassist(anchors[1,,drop=FALSE], exposure[1,,drop=FALSE], targets, nodiag=TRUE)
```

In both scenarios I have checked the top sub-matrix of `targets` is the same as `exposure`, and that the columns are in the same order across matrices, and I have initialised findr with the same random seed.

From your paper it seems to me that the likelihood ratio estimates are calculated for each pair of exposures (A) and targets (B) separately, so there should be no difference in posterior probabilities when running findr in these two different ways - however I may have missed something since I find algebraic formulae difficult to parse.

The reason I have investigated this second approach is that I would like to be able to run findr with multiple causal anchors per gene (e.g. multiple conditionally independent cis-eQTLs). Following a similar reasoning to Mendelian Randomisation, if gene A is truly causal of gene B, you would expect to see strong posterior probabilities of causality for all of A's eQTLs. Having multiple causal anchors would therefore allow us to add additional confidence to Findr's posterior probability calls (e.g. by taking the median across anchors for each gene, or adapting the [MR-egger approach](http://onlinelibrary.wiley.com/doi/10.1002/gepi.21965/full)). The way the software is currently implemented, the only way to incorporate multiple causal anchors is to loop through each anchor-gene pair and test against all outcomes to avoid the issue of testing causality of a gene against itself in a non-diagonal matrix entry.

**Comment by sritchie73** [comment]
Related to #5 - there were two perfectly correlated genes in the exposure matrix, leading to dramatically different posterior probabilities between these two approaches. After removing one of the two perfectly correlated genes, the posterior probabilities are correlated, but still quite different, between the two approaches above.

Here's an ASCII scatterplot of the posterior probabilities using the approach as intended (x-axis) vs looping through each gene separately (y-axis) for 232 genes tested for causality on 1129 genes:

```
    +--+---------+----------+----------+---------+----------+--+
  1 +                              *     ** **** ************  +
    |                            ******** ****************     |
0.8 +                           **********************         +
    |                          **********************  *       |
    |                         ********************             |
0.6 +                       ****************                   +
    |                   ***********************                |
0.4 +             **********************                       +
    |     **********************                               |
    |    *******************                                   |
0.2 +  *****************                                       +
    |  *************                                           |
  0 +  **********                                              +
    +--+---------+----------+----------+---------+----------+--+
       0        0.2        0.4        0.6       0.8         1   
```

**Comment by lingfeiwang** [comment]
Hi,

To respond to your first post, that's indeed the correct behaviour of Findr. This is because findr.pij_[cg]assist in Findr uses a bin-based computation of posterior probability p(H_alt|LLR) which also skips the computation of p-values. Since the bins depend on the whole data, the posterior probability may vary with the size of your input, or the chunk size when memlimit is set in the binary or python interface. This is mentioned in Text S1.1 of https://doi.org/10.1371/journal.pcbi.1005703, though not explicitly on the data size dependency.

If you want the result to be independent of the data size, one option is to compute the posterior probabilities yourself from the p-values. To do that, first compute p-values for all tests using findr.pijs_cassist_pv, and then convert them to 1-local FDRs using the fdrtool package, separately for each regulator/exposure. In the end, you will need to combine the posterior probabilities (i.e. 1-local FDRs) on your own into the composite novel test. Findr doesn't work in this way partly because I didn't find a library for grenader estimator. Btw, findr.pijs_cassist_pv should be independent of data size.

Regarding your attempt to use multiple cis-eQTLs, we have also done some unpublished work on real data but didn't find any significant improvement. That was probably due to the correlation between different cis-eQTLs. On orthogonal cis-eQTLs things could be different, and I am looking forward to seeing how your research goes. The above mentioned custom pipeline should give you more flexibility, such as combining cis-eQTLs at p-value or posterior probability levels. We also have a recent preprint demonstrating unsupervised ensemble learning is actually dimension reduction, and therefore simply PCA or Isomap can outperform the best method on the market (https://arxiv.org/pdf/1711.11034).

**Comment by lingfeiwang** [comment]
Update:

I looked into the code. It seems **NOT** the intended behaviour. The output depends on the size of the target but should not depend on that of the exposure. I will look into it and return to you shortly.

**Comment by lingfeiwang** [comment]
Final examination indicated that Findr performs as intended. The LLR histograms are constructed separately for each exposure. However, the histograms use the same bounds that depend on the global maximum LLR, which therefore introduces dependency on other regulators.

If I remember it correctly (it was a long time ago), I implemented it as such because even the analytical computation of null distributions takes some time when it was done separately for different histogram bounds of each regulator. Special functions are slow too.

Anyway, Findr still leaves you the possibility of using different histogram bounds for each regulator, i.e. the separation of computation you are already using. Integration with fdrtool is also possible in R.

**Comment by sritchie73** [comment]
Hi,

Thanks so much for looking into that and explaining what's going on!
