### ISSUE TITLE
Error should be returned when `nodiag` is violated 

### ISSUE THREAD

**Issue by sritchie73** [lingfeiwang/findr-R#5]
Another problem I came across while investigating #4 :

If genes are tested against themselves in `findr.pij_cassist`, findr will run without warnings or errors, but the posterior probabilities returned for *other pairs of tested genes* are sometimes dramatically different (e.g. if run correctly A -> B might be 0.01, while if run where A -> A is tested elsewhere A -> B could be 0.8, or vice versa).

Scenarios where this can occur:

 - A user mistakenly does not set `nodiag=TRUE`.
 - A user mistakenly does not order `dt2` so that its top matrix is `dt` (i.e. self-tests are not on the diagonal).
 - Cases where there are perfectly correlated genes in the `dt` matrix.

Ideally findr should detect input matrices where this assumption has been violated and throw an error.

**Comment by lingfeiwang** [comment]
That's definitely a good point. In fact, findr already tests it in the computation, using the 3rd point you mentioned. However, due to nearest rounding, it warns only some of the time. If you consider the time complexity of a separate sanity test, it is actually quite expensive by being the same with the whole computation. I just came up with an efficient test, so this function will be included in the next version. Thank you for suggesting.

**Comment by lingfeiwang** [comment]
Sanity check added in v1.0.6.
