### ISSUE TITLE
Error in findr.netr_one_greedy(ans) :    long vectors (argument 2) are not supported in .C

### ISSUE THREAD

**Issue by whtop** [lingfeiwang/findr-R#6]
ans1 = findr.pij_gassist(genotype, mVals, mVals, nodiag=T).
Here, genotype is 60000 X 700， and mVals is 60000 X 700.
I get the above error.

Or, when using: net = findr.netr_one_greedy(ans)
When ans is a matrix of 60000 X 60000.
And I also get the above error.

When the matrix size is small, there is no error.

**Comment by lingfeiwang** [comment]
Hi whtop,

It seems to be a similar issue with [this](https://stackoverflow.com/questions/34165654/r-vector-size-limit-long-vectors-argument-5-are-not-supported-in-c) due to R's internal limits of parameter size in function .C.

The workaround using R's .Call function requires quite some refactoring of the code which we have no intention of implementing at the moment. Also, R is quite memory intensive compared to python or C. With large input sizes, we would recommend the [binary](https://github.com/lingfeiwang/findr-bin) or [python](https://github.com/lingfeiwang/findr-python) interface instead. Note that they need separate, prior installation of the [findr library](https://github.com/lingfeiwang/findr). If you really need the program in R, the [reticulate](https://rstudio.github.io/reticulate/) package might help.

Please let us know if these solutions don't work.

**Comment by whtop** [comment]
Thanks, python works.
